on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '**'

name: test

jobs:
  test:
    name: test
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: brew check
      run: |
        brew list
        brew update
        brew upgrade
    - name: check
      run: |
        echo $PATH
        which python3
        which python
    - name: npm install, make test-coverage
      run: |
        npm install
        make test-coverage
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

